### ISSUE TITLE
OpenSSL wrong version number from

### ISSUE THREAD

**Issue by mhenrixon** [yousty/event_store_client#46]
```ruby
FakeIt.until_you_make_it!
#=> OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
```

Given the following configuration

```ruby
# config/initializers/event_store_client.rb

require 'event_store_client'
require "event_store_client/adapters/grpc"

EventStoreClient.configure do |config|
  config.adapter = :grpc
  config.eventstore_url = ENV['EVENTSTORE_URL']
  config.service_name = 'bogus'
  config.verify_ssl = false
end
```

Used by this code

```ruby
require 'faker'

class MessageEvent < EventStoreClient::DeserializedEvent
  def schema
    Dry::Schema.Params do
      required(:from_id).value(:integer)
      required(:to_id).value(:integer)
      required(:message).value(:string)
      required(:created_at).value(:time)
    end
  end
end

module FakeIt
  extend self

  USER_IDS = [123, 432].freeze

  def until_you_make_it!
    10_000.times do
      event_store.publish(
        stream: 'messages',
        events: [build_event]
      )
    end
  end

  private

  def sample_user(exclude_id = nil)
    return USER_IDS.sample(1) if exclude_id.nil?

    USER_IDS.reject { |id| id == exclude_id }.first
  end

  def build_event
    from_id = sample_user
    to_id   = sample_user(from_id)
    message = Faker::Lorem.unique.sentence

    MessageEvent.new(
      data: {
        from_id: from_id,
        to_id: to_id,
        message: message,
        created_at: Time.current
      }
    )
  end

  def event_store
    @event_store ||= EventStoreClient::Client.new
  end
end
```

The dependency on grpc wasn't super easy to install:

```console
apk --no-cache add --update --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main gcompat protobuf grpc
```

But seems to have done the trick. Unfortunately, I don't know what is upp with eventstore:

```yaml
  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      EVENTSTORE_CLUSTER_SIZE: "1"
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_EXT_TCP_PORT: "1113"
      EVENTSTORE_HTTP_PORT: "2113"
      EVENTSTORE_INSECURE: "false"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
```

Any ideas what might be wrong?
